### ISSUE TITLE
这个问题怎么解决

### ISSUE THREAD

**Issue by zx26424** [Aruelius/jd_maotai#13]
和京东服务器时差为：172
Traceback (most recent call last):
  File "E:/jd_maotai-main/main.py", line 147, in <module>
    mt.main()
  File "E:/jd_maotai-main/main.py", line 108, in main
    address_info = self.init_action()
  File "E:/jd_maotai-main/main.py", line 38, in init_action
    return r.json()
  File "D:\anaconda\lib\site-packages\requests\models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "D:\anaconda\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "D:\anaconda\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\anaconda\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by bushizhangwudia** [comment]
同问
