### ISSUE TITLE
提示 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by iseeyou** [Aruelius/jd_maotai#6]
和京东服务器时差为：-1187
Traceback (most recent call last):
  File "D:\SoftWare\jd_maotai-main\main.py", line 147, in <module>
    mt.main()
  File "D:\SoftWare\jd_maotai-main\main.py", line 109, in main
    if address_info.get("islogin") == "-1":
AttributeError: 'NoneType' object has no attribute 'get'
---------------------------
建议将 self.buy_time 改下自动识别当前日期

**Comment by Aruelius** [comment]
说明 cookie 没设置好

**Comment by zx26424** [comment]
不一样的报错。。


和京东服务器时差为：172
Traceback (most recent call last):
File "E:/jd_maotai-main/main.py", line 147, in
mt.main()
File "E:/jd_maotai-main/main.py", line 108, in main
address_info = self.init_action()
File "E:/jd_maotai-main/main.py", line 38, in init_action
return r.json()
File "D:\anaconda\lib\site-packages\requests\models.py", line 898, in json
return complexjson.loads(self.text, **kwargs)
File "D:\anaconda\lib\json_init_.py", line 357, in loads
return _default_decoder.decode(s)
File "D:\anaconda\lib\json\decoder.py", line 337, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "D:\anaconda\lib\json\decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
